/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ViewRegister;

import Configuration.MsgBoxDialog;
import Controller.ChangeViewController;
import Controller.DAOFindController;
import Controller.DAORegisterController;
import Model.Bean.Book;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author XXXXXX
 */
public class ViewDoLending extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRealizarEmprestimo
     * @param j
     */
    public ViewDoLending() {
        initComponents();
        this.btnDoLending.setVisible(false);
        DAOFindController.fillJComboBoxBooks(jComboBoxListaLivros);
        DAOFindController.fillJTableExemplarys(jTableExemplarys, (Book)this.jComboBoxListaLivros.getSelectedItem());
        ChangeViewController.addColorOnRows(jTableExemplarys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxListaLivros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExemplarys = new javax.swing.JTable();
        btnDoLending = new javax.swing.JButton();

        setClosable(true);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Livro");

        jComboBoxListaLivros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxListaLivrosItemStateChanged(evt);
            }
        });
        jComboBoxListaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListaLivrosActionPerformed(evt);
            }
        });

        jTableExemplarys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Disponibilidade", "Id Livro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExemplarys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExemplarysMouseClicked(evt);
            }
        });
        jTableExemplarys.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableExemplarysKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExemplarys);

        btnDoLending.setText("Realizar empréstimo");
        btnDoLending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoLendingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBoxListaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnDoLending, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxListaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnDoLending, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxListaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListaLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaLivrosActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        MsgBoxDialog.showMsgYesNo(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnDoLendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoLendingActionPerformed
        if(this.jTableExemplarys.getSelectedRows().length==1){
            if(DAORegisterController.insertLending(this)){
                JOptionPane.showMessageDialog(rootPane, "Empréstimo realizado com sucesso");
                DAOFindController.fillJTableExemplarys(jTableExemplarys, (Book)this.jComboBoxListaLivros.getSelectedItem());
                ChangeViewController.addColorOnRows(jTableExemplarys);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Este livro já está em um empréstimo ou o usuário já possui um exemplar deste livro");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Somente um exemplar por livro pode ser alocado para um empréstimo");
        }
    }//GEN-LAST:event_btnDoLendingActionPerformed

    private void jComboBoxListaLivrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxListaLivrosItemStateChanged
        DAOFindController.fillJTableExemplarys(jTableExemplarys, (Book)this.jComboBoxListaLivros.getSelectedItem());
        ChangeViewController.addColorOnRows(jTableExemplarys);
    }//GEN-LAST:event_jComboBoxListaLivrosItemStateChanged

    private void jTableExemplarysKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableExemplarysKeyReleased
        this.btnDoLending.setVisible(true);
    }//GEN-LAST:event_jTableExemplarysKeyReleased

    private void jTableExemplarysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExemplarysMouseClicked
        this.btnDoLending.setVisible(true);
    }//GEN-LAST:event_jTableExemplarysMouseClicked

    public JTable getjTableExemplarys() {
        return jTableExemplarys;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoLending;
    private javax.swing.JComboBox<Object> jComboBoxListaLivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExemplarys;
    // End of variables declaration//GEN-END:variables
}
