/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ViewDelete;

import Controller.ChangeViewController;
import Controller.DAODeleteController;
import Controller.DAOFindController;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author XXXXXX
 */
public class ViewDeleteExemplary extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewDeleteExemplary
     */
    public ViewDeleteExemplary() {
        initComponents();
        DAOFindController.fillJTableExemplarys(jTableExemplarys);
        ChangeViewController.addColorOnRows(jTableExemplarys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExemplarys = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);

        jTableExemplarys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Disponibilidade", "Id Livro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableExemplarys);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(this.jTableExemplarys.getSelectedRow()!=-1){
            if(DAODeleteController.deleteExemplary(this)){
                JOptionPane.showMessageDialog(rootPane, "Exemplares excluídos com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Algum exemplar não foi excluído");
            }
            DAOFindController.fillJTableExemplarys(jTableExemplarys);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione ao menos uma linha da tabela");
        }
            
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExemplarys;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableExemplarys() {
        return jTableExemplarys;
    }
    
}
